name: Dependency Management

on:
  schedule:
    - cron: '0 9 * * MON' # Weekly on Mondays at 9 AM
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor # Only run on original repo, not forks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Update dependencies
      run: |
        # Update non-breaking changes
        npx npm-check-updates -u --target minor
        npm install
        
        # Run tests to ensure nothing broke
        npm run lint
        npx tsc --noEmit

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          ## 🤖 Automated Dependency Updates
          
          This PR updates dependencies to their latest minor versions.
          
          ### Changes
          - Updated package.json dependencies
          - Ran linting and type checking to verify compatibility
          
          ### Testing
          - ✅ ESLint passed
          - ✅ TypeScript compilation successful
          
          Please review the changes and run full tests before merging.
        branch: automated/dependency-updates
        delete-branch: true

  audit-fix:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit fix
      run: |
        npm audit fix --audit-level moderate
        npm install # Ensure lock file is updated

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'fix: automated security vulnerability fixes'
        title: 'fix: security vulnerability fixes via npm audit'
        body: |
          ## 🔒 Automated Security Fixes
          
          This PR applies automatic fixes for security vulnerabilities found by npm audit.
          
          ### Changes
          - Applied `npm audit fix` to resolve security issues
          - Updated package-lock.json
          
          ⚠️ **Important**: Please review these changes carefully and run full tests before merging.
        branch: automated/security-fixes
        delete-branch: true